FROM mcr.microsoft.com/devcontainers/base:ubuntu
RUN apt-get update
RUN sudo apt-get install -y \
  btrfs-progs \
  gcc \
  git \
  golang-go \
  go-md2man \
  iptables \
  libassuan-dev \
  libbtrfs-dev \
  libc6-dev \
  libdevmapper-dev \
  libglib2.0-dev \
  libgpgme-dev \
  libgpg-error-dev \
  libprotobuf-dev \
  libprotobuf-c-dev \
  libseccomp-dev \
  libselinux1-dev \
  libsystemd-dev \
  make \
  containernetworking-plugins \
  podman \
  pkg-config \
  runc \
  uidmap